### ISSUE TITLE
ADD A .GITIGNORE FILE

### ISSUE THREAD

**Issue by BaharaJr** [lazaropower/mern-app#1]
Hello, always add a .gitinore file to ignore build files and node modules

[Here is a quick setup site](https://www.toptal.com/developers/gitignore)

All you need to do is add the OS you are using, IDE, languages and let it generate everything for you

**Comment by lazaropower** [comment]
Hi there, thanks for the advice. Just added 😄

**Comment by BaharaJr** [comment]
You are welcome
